name: Java CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Maven version
      run: mvn --version
    - name: Build with Maven
      env:
        MAVEN_OPTS: -Dmaven.wagon.http.retryHandler.count=3
      run: mvn --quiet -B install --file pom.xml -s .github/maven/settings.xml -DenableAssertions=false
    - name: Push Docker images
      env:
        DOCKER_USER: ${{ secrets.DockerUser }}
        DOCKER_PASSWORD: ${{ secrets.DockerPassword }}
      run: |
        echo $DOCKER_PASSWORD | docker login ghcr.io -u $DOCKER_USER --password-stdin
        mvn package --file pom.xml -s .github/maven/settings.xml -Pdocker -DenableAssertions=false -DskipTests
        docker push ghcr.io/${{ github.repository }}-core:latest
        docker push ghcr.io/${{ github.repository }}-coherence:latest
        docker push ghcr.io/${{ github.repository }}-mongo:latest
        docker push ghcr.io/${{ github.repository }}-mysql:latest
        docker push ghcr.io/${{ github.repository }}-redis:latest
        docker push ghcr.io/${{ github.repository }}-core:2.2.0
        docker push ghcr.io/${{ github.repository }}-coherence:2.2.0
        docker push ghcr.io/${{ github.repository }}-mongo:2.2.0
        docker push ghcr.io/${{ github.repository }}-mysql:2.2.0
        docker push ghcr.io/${{ github.repository }}-redis:2.2.0
      if: github.event_name == 'push'
